name: google_maps_cluster_manager
description: Simple Flutter clustering library for Google Maps based on Geohash.
version: 0.2.0
homepage: https://github.com/bpillon/google_maps_cluster_manager

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  geohash: ^0.2.1
  google_maps_flutter: ^1.0.5
  google_maps_flutter_web: ^0.1.0+8

dev_dependencies:
  flutter_test:
    sdk: flutter
